package com.jia.demo.db.domain;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jia.demo.db.domain.AA;

import com.jia.demo.db.domain.AADao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aADaoConfig;

    private final AADao aADao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aADaoConfig = daoConfigMap.get(AADao.class).clone();
        aADaoConfig.initIdentityScope(type);

        aADao = new AADao(aADaoConfig, this);

        registerDao(AA.class, aADao);
    }
    
    public void clear() {
        aADaoConfig.getIdentityScope().clear();
    }

    public AADao getAADao() {
        return aADao;
    }

}
